# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/


services:
  next-app:
    container_name: next-app
    build:
      context: .
      args:
        - NODE_ENV=development
    hostname: ${DOMAIN_NAME}
    ports:
      - 3000:3000
      - 3001:3001 # For HTTPS
    extra_hosts:
      - "${DOMAIN_NAME}:127.0.0.1"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BASE_URL=https://${DOMAIN_NAME}:443
      - NODE_EXTRA_CA_CERTS=/app/certs/${DOMAIN_NAME}.crt
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
      - STRIPE_SECRET_KEY
      - STRIPE_BASIC_PRICE_ID
      - STRIPE_BASIC_LINK
      - STRIPE_PRO_PRICE_ID
      - STRIPE_PRO_LINK
      - STRIPE_ENTERPRISE_PRICE_ID
      - STRIPE_ENTERPRISE_LINK
    command: npm run dev:https
    volumes:
      - .:/app
      - /app/node_modules
      - ./certs:/app/certs
    env_file:
      - .env
    restart: unless-stopped
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
    networks:
      - next-app-network

  nginx:
    container_name: next-app-nginx
    networks:
      - next-app-network
    image: nginx:alpine
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - next-app
    extra_hosts:
      - "${DOMAIN_NAME}:127.0.0.1"

networks:
  next-app-network:
    driver: bridge
